### ISSUE TITLE
Error When pip install bbrf

### ISSUE THREAD

**Issue by un1tycyb3r** [honoki/bbrf-client#111]
I get this error when attempting to install bbrf client:

ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 324, in run
    session = self.get_default_session(options)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/network/session.py", line 342, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/network/session.py", line 140, in user_agent
    linux_distribution = distro.name(), distro.version(), distro.codename()
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 319, in name
    return _distro.name(pretty)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 864, in name
    self.os_release_attr("name")
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 1057, in os_release_attr
    return self._os_release_info.get(attribute, "")
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 1096, in _os_release_info
    return self._parse_os_release_content(release_file)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 1117, in _parse_os_release_content
    tokens = list(lexer)
  File "/usr/lib/python3.10/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.10/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.10/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main.py", line 79, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 225, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 180, in handle_pip_version_check
    session = self._build_session(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/network/session.py", line 342, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/network/session.py", line 140, in user_agent
    linux_distribution = distro.name(), distro.version(), distro.codename()
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 319, in name
    return _distro.name(pretty)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 864, in name
    self.os_release_attr("name")
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 1057, in os_release_attr
    return self._os_release_info.get(attribute, "")
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 1096, in _os_release_info
    return self._parse_os_release_content(release_file)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 1117, in _parse_os_release_content
    tokens = list(lexer)
  File "/usr/lib/python3.10/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.10/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.10/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 62, in apport_excepthook
    import apport.report
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 4, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl/__init__.py", line 30, in <module>
    impl = load_packaging_implementation()
  File "/usr/lib/python3/dist-packages/apport/packaging_impl/__init__.py", line 25, in load_packaging_implementation
    f"apport.packaging_impl.{determine_packaging_implementation()}"
  File "/usr/lib/python3/dist-packages/apport/packaging_impl/__init__.py", line 9, in determine_packaging_implementation
    info = freedesktop_os_release()
  File "/usr/lib/python3.10/platform.py", line 1292, in freedesktop_os_release
    _os_release_cache = _parse_os_release(f)
  File "/usr/lib/python3.10/platform.py", line 1272, in _parse_os_release
    for line in lines:
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main.py", line 79, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 225, in _main
    self.handle_pip_version_check(options)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 180, in handle_pip_version_check
    session = self._build_session(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/network/session.py", line 342, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/network/session.py", line 140, in user_agent
    linux_distribution = distro.name(), distro.version(), distro.codename()
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 319, in name
    return _distro.name(pretty)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 864, in name
    self.os_release_attr("name")
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 1057, in os_release_attr
    return self._os_release_info.get(attribute, "")
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 1096, in _os_release_info
    return self._parse_os_release_content(release_file)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/distro/distro.py", line 1117, in _parse_os_release_content
    tokens = list(lexer)
  File "/usr/lib/python3.10/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.10/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.10/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte

**Comment by un1tycyb3r** [comment]
Cloning the repo and running python3 setup.py install works however

**Comment by pdelteil** [comment]
This error is related to your python/pip install rather than bbrf.
