### ISSUE TITLE
[Issue] Exception: not_found

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#19]
Hello there,

Managed to install CouchDB and the client, I needed to modify the file bbrf_api.py to allow requests to my server with a self-signed certificate, so I just added _verify=False_ to all self.requests_session functions. 

I manage to create programs and their scope/domains, but I can't retrieve them:
```
 > bbrf programs 

Traceback (most recent call last):
  File "/home/kali/software/bbrf-client/bbrf.py", line 828, in <module>
    result = bbrf.run()
  File "/home/kali/software/bbrf-client/bbrf.py", line 666, in run
    return self.list_domains(self.arguments['--all'])
  File "/home/kali/software/bbrf-client/bbrf.py", line 565, in list_domains
    return self.api.get_domains_by_program_name()
  File "/home/kali/software/bbrf-client/bbrf_api.py", line 45, in get_domains_by_program_name
    raise Exception(r.json()['error'])
Exception: not_found

```

```
> bbrf domains --all

Traceback (most recent call last):
  File "/home/kali/software/bbrf-client/bbrf.py", line 828, in <module>
    result = bbrf.run()
  File "/home/kali/software/bbrf-client/bbrf.py", line 666, in run
    return self.list_domains(self.arguments['--all'])
  File "/home/kali/software/bbrf-client/bbrf.py", line 565, in list_domains
    return self.api.get_domains_by_program_name()
  File "/home/kali/software/bbrf-client/bbrf_api.py", line 45, in get_domains_by_program_name
    raise Exception(r.json()['error'])
Exception: not_found

```

```
bbrf new OK 
/home/kali/software/bbrf-client/.env/lib/python3.9/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'info-sec.cl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
```
![Screenshot from 2021-01-20 01-27-23](https://user-images.githubusercontent.com/20244863/105127038-bc0a2680-5abe-11eb-94c9-418f9f461d88.png)

What could be the problem?

**Comment by honoki** [comment]
Did you follow this step from the docs:

> Configure the required views via curl:

```
curl -X PUT $COUCHDB"bbrf/_design/bbrf" \
     -u admin:password \
     -H "Content-Type: application/json" \
     -d @views.json

**Comment by pdelteil** [comment]
In my script that line was inadvertently commented. Thanks.
