### ISSUE TITLE
Unable to remove blacklist element

### ISSUE THREAD

**Issue by xqd-ai** [honoki/bbrf-client#25]
when trying to delete a blacklist element from a program, I get bellow error

```
$ bbrf blacklist add www.example.com -p example.com
$ bbrf blacklist remove www.example.com -p example.com
Traceback (most recent call last):
  File "/root/bbrf-client/bbrf.py", line 935, in <module>
    result = bbrf.run()
  File "/root/bbrf-client/bbrf.py", line 884, in run
    self.remove_blacklist(self.arguments['<element>'])
  File "/root/bbrf-client/bbrf.py", line 694, in remove_blacklist
    blacklist.delete(e)
AttributeError: 'list' object has no attribute 'delete'
```

**Comment by xqd-ai** [comment]
I fixed the error by changing line 694's statment 'blacklist.delete(e)' to 'blacklist.remove(e)' and it worked

**Comment by honoki** [comment]
Thanks for pointing this out. I have fixed this and added some tests to my test suite so the scenario is properly covered.
