### ISSUE TITLE
Error when adding domain with the tag option

### ISSUE THREAD

**Issue by xqd-ai** [honoki/bbrf-client#26]
Hi,
I get bellow error when I try to add a domain to a program with the tag option `-t`:

```
# bbrf domain add www.example.com -p example.com -t test
Traceback (most recent call last):
  File "/root/bbrf-client/bbrf.py", line 935, in <module>
    result = bbrf.run()
  File "/root/bbrf-client/bbrf.py", line 765, in run
    return self.add_domains(self.arguments['<domain>'])
  File "/root/bbrf-client/bbrf.py", line 255, in add_domains
    success, _ = self.api.add_documents('domain', add_domains, self.get_program(), source=self.arguments['-s'], tags=self.arguments['-t'])
  File "/root/bbrf-client/bbrf_api.py", line 233, in add_documents
    tag_map = {x.split(':', 1)[0]: x.split(':', 1)[1] for x in tags}
  File "/root/bbrf-client/bbrf_api.py", line 233, in <dictcomp>
    tag_map = {x.split(':', 1)[0]: x.split(':', 1)[1] for x in tags}
IndexError: list index out of range


```

**Comment by honoki** [comment]
Hi - to add a tag, use the syntax `-t name:value`. 

See https://github.com/honoki/bbrf-client/issues/11#issuecomment-760291941 for more details.
