### ISSUE TITLE
Error while adding a tag to a new program

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-client#37]
Commands

>**bbrf new 1testing -t site** 
```
Traceback (most recent call last):
  File "/home/kali/.local/bin/bbrf", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.9/site-packages/bbrf/bbrf.py", line 986, in main
    result = bbrf.run()
  File "/home/kali/.local/lib/python3.9/site-packages/bbrf/bbrf.py", line 771, in run
    self.new_program()
  File "/home/kali/.local/lib/python3.9/site-packages/bbrf/bbrf.py", line 101, in new_program
    self.api.create_new_program(self.get_program(), tags=self.arguments['-t'])
  File "/home/kali/.local/lib/python3.9/site-packages/bbrf/bbrf_api.py", line 39, in create_new_program
    tag_map = {x.split(':', 1)[0]: x.split(':', 1)[1] for x in tags}
  File "/home/kali/.local/lib/python3.9/site-packages/bbrf/bbrf_api.py", line 39, in <dictcomp>
    tag_map = {x.split(':', 1)[0]: x.split(':', 1)[1] for x in tags}
IndexError: list index out of range

```

And then without the -t flag

```
> bbrf new 1testing
(no output) 
```

**Comment by honoki** [comment]
Hi @pdelteil - the tagging syntax should always look like `-t key:value`. Please try that and let me know if that solves the issue.

**Comment by pdelteil** [comment]
Hello @honoki,

I just updated from 1.0.6, so the way I was using to create new programs changed. 

I don't understand what should I do to keep old and new programs consistent ? 

For instance, let's say I use:

`` bbrf new TEST -t site:bugcrowd 
``

What should I do to programs created with the old versions?

**Comment by pdelteil** [comment]
> Hi @pdelteil - the tagging syntax should always look like `-t key:value`. Please try that and let me know if that solves the issue.

Using the tag syntax you mentioned solved the issue.

**Comment by honoki** [comment]
You should be able to update a program (or multiple programs) with the same syntax:

```
bbrf program update test test2 test3 -t key:value
```

**Comment by pdelteil** [comment]
Thanks.
